#!/bin/bash

while ! [[ -e /sys/bus/usb/devices/2-3/2-3:1.0/net/wwp0s20f0u3 ]]; do
    sleep 1
done

sleep 1

echo 16383 > /sys/bus/usb/devices/2-3/2-3:1.0/net/wwp0s20f0u3/cdc_ncm/rx_max
echo 16383 > /sys/bus/usb/devices/2-3/2-3:1.0/net/wwp0s20f0u3/cdc_ncm/tx_max
echo 16384 > /sys/bus/usb/devices/2-3/2-3:1.0/net/wwp0s20f0u3/cdc_ncm/rx_max
echo 16384 > /sys/bus/usb/devices/2-3/2-3:1.0/net/wwp0s20f0u3/cdc_ncm/tx_max

systemctl start ModemManager.service
